# Generated by Django 4.0.4 on 2022-06-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_followertable_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialProfileUser',
        ),
    ]
